language: node_js
node_js:
  - "0.10"
  - "0.11"
  - "0.12"
  - "iojs"
script: date | sha1sum | haste() { a=$(cat); curl -X POST -s -d "$a" http://hastebin.com/documents | awk -F '"' '{print "http://hastebin.com/"$4}'; } 
cache:
  directories:
    - node_modules
sudo: false
